# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AmazonConnectChatiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AmazonConnectChatiOS
  pod 'AWSCore'
  pod 'AWSConnect'
  pod 'AWSConnectParticipant'
  pod 'Starscream', '~> 3.1'

  target 'AmazonConnectChatiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AmazonConnectChatiOSUITests' do
    # Pods for testing
  end

end
